name: Level-3 (Context & Expression)

on:
  - push
  - workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Print Current Date
        run: "echo Current date and time is: $(date)"

      - name: Print Repository Name
        run: "echo Repository name is: ${{ github.repository }}"

      - name: Print Event Name
        run: "echo Event name is: ${{ github.event_name }}"

      - name: Print Commit SHA
        run: "echo Commit SHA is: ${{ github.sha }}"

      - name: Print Branch or Tag
        run: "echo Branch or tag is: ${{ github.ref }}"

      - name: Print Actor
        run: "echo Actor is: ${{ github.actor }}"

      - name: Print Runner OS
        run: "echo Runner OS is: ${{ runner.os }}"

      - name: Print Github Context
        run: echo "${{ toJson(github) }}"
