name: Level-4 (activity types & filters)

on:
  pull_request:
    types: [opened, edited]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: PR just happened
        run: echo "A NEW PR WAS JUST OPENED...!"